name = "web-start"
compatibility_date = "2024-01-01"

[env.production.vars]
VITE_API_URL = "https://your-render-backend.onrender.com"

# For preview/staging deployments
[env.preview.vars]
VITE_API_URL = "https://your-render-backend.onrender.com"
